version: 2.1

orbs:
  node: circleci/node@5.0.2

workflows:
  default:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                - "14.4"
                - "12.18"
